### ISSUE TITLE
Can I send a patch to the hardware?

### ISSUE THREAD

**Issue by 4ndrw** [JoeMatt/BassStationIIMaxForLive#1]
I can see a way to capture a patch from the hardware (which is the main thing I wanted this for)

but if the gui ends up different from the hardware, 
- Maybe I'm saving a few instances in a project
(eg. say I have 3 different bass station patches used in the song, but some are recorded to audio etc)
- Or I've changed patch on the hardware but want it to now sync back up with the plugin

Is there a button to send the patch in the device to the hardware?

Or is this something I should try and work out how to build if I want it?

**Comment by 4ndrw** [comment]
Also, there's a great way to load syx files, is there a way to save a syx file from this?

**Comment by 4ndrw** [comment]
(sorry for the million questions, I know this is an old project for you!)

**Comment by 4ndrw** [comment]
Also I'm confused why the internal sysex doesn't work and it only works with the router

when I follow the signal path it looks like it should

**Comment by 4ndrw** [comment]
It's elegant the way you've decoded the sysex from the synth!

**Comment by JoeMatt** [comment]
> Also I'm confused why the internal sysex doesn't work and it only works with the router
> 
> when I follow the signal path it looks like it should

When I wrote this, Ableton didn't support sysex for device chains at all. It probably needs an update now that Ableton doesn't filter sysex to max devices (thought i did this, maybe I have an old version here).

> Also, there's a great way to load syx files, is there a way to save a syx file from this?
No, but you can use the official Novation apps to generate them, I believe this is where the included patch banks come from. Just export and load using the devices systex dump.

I thought about adding that feature, but again, at the time sysex was a pain to handle in Ableton.

**Comment by JoeMatt** [comment]
> I can see a way to capture a patch from the hardware (which is the main thing I wanted this for)
> 
> but if the gui ends up different from the hardware,
> 
> * Maybe I'm saving a few instances in a project
>   (eg. say I have 3 different bass station patches used in the song, but some are recorded to audio etc)
> * Or I've changed patch on the hardware but want it to now sync back up with the plugin
> 
> Is there a button to send the patch in the device to the hardware?
> 
> Or is this something I should try and work out how to build if I want it?

You can create a snapshot of the patch setting in Ableton as a native preset state.
I'm pretty sure this works last I tested it. When the preset for the device loads, it dumps the patch to the device. (this is the same as loading a saved Ableton project with this device in it, it will bang the patch to the device on open) You can also forcibly update using the button that I'm pretty sure I remember being there too (sorry I forgot the details I haven't used this device myself in a few years, I only recently updated here since the dropbox links were dead and I got a bunch of emails to re-upload)

**Comment by 4ndrw** [comment]
Really appreciate you reuploading it!

I can't find the button, if you can recall how to do it, that'd be ace

if not, I'll see if I can work it out <3

**Comment by 4ndrw** [comment]
Maybe this is 1.5 and not 2.0?

Either way, there's lots of great work in here!
